" Options
set autochdir
set autoindent
set background=dark
set backspace=indent,eol,start
set expandtab
set hlsearch
set ignorecase
set incsearch
set noswapfile
set number
set relativenumber
set scrolloff=3
set shiftwidth=2
set smartcase
set softtabstop=2
set splitbelow
set splitright
set term=xterm-256color
set termguicolors

" Commands
syntax on

" Plugins
packadd! dracula
colorscheme dracula

let g:loaded_matchparen=1

